### ISSUE TITLE
Wrong SPARQL request and wrong Properties for question 

### ISSUE THREAD

**Issue by mdsalnikov** [vladislavneon/RuBQ#2]
SPARQL request from this one question returned empty results.
https://github.com/vladislavneon/RuBQ/blob/fade3eae6a4807c35b19cfce20dfa805fc8c0cdf/RuBQ_2.0/RuBQ_2.0_dev.json#L13003

question_props not connected to question_uri and has no logical connections.

**Comment by vladislavneon** [comment]
That happens because Wikidata is changing over time. As you can see, [this version](https://www.wikidata.org/w/index.php?title=Q29428373&oldid=1088632455) of entity Q29428373 (tetrad) has property P1557 which leads to correct answer

It is why we recommend to use our Wikidata dump with RuBQ
